/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Rota publica usada pelo GitHub Actions para manter a instancia do Render
         *     acordada. Nao deve tocar no banco de dados em caminho critico; o campo
         *     `database` faz um SELECT 1 com timeout curto e degrada para "down" sem
         *     derrubar a resposta.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfil do organizador autenticado
         * @description Retorna os dados do organizador derivados do JWT. Na primeira chamada o
         *     backend cria o registro local em `organizers` (upsert por `sub`), o que
         *     dispensa um fluxo de cadastro proprio.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os eventos do organizador autenticado */
        get: operations["listEvents"];
        put?: never;
        /**
         * Cria um evento
         * @description O evento nasce sempre com status `draft`.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Detalhe de um evento */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /**
         * Cancela um evento
         * @description Soft delete. O evento passa para `cancelled` e todos os ingressos
         *     `valid` passam para `revoked`. Historico de check-ins e preservado.
         */
        delete: operations["cancelEvent"];
        options?: never;
        head?: never;
        /**
         * Atualiza um evento
         * @description Atualizacao parcial. Campos ausentes no corpo permanecem inalterados.
         *     Eventos com status `finished` ou `cancelled` sao imutaveis (409).
         */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/api/v1/events/{event_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publica um evento
         * @description Transicao `draft` -> `published`. Exige `starts_at` no futuro e
         *     `capacity` definida. Depois de publicado, o evento aceita emissao de
         *     ingressos.
         */
        post: operations["publishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Lista os ingressos de um evento */
        get: operations["listTickets"];
        put?: never;
        /**
         * Emite um lote de ingressos
         * @description Emissao em lote (1 a 500 por chamada). Operacao transacional: ou todos os
         *     ingressos sao criados, ou nenhum. Se a soma dos ingressos existentes com
         *     os novos ultrapassar `capacity`, retorna 409 `EVENT_CAPACITY_EXCEEDED`.
         *
         *     Esta e a UNICA resposta da API que devolve o `qr_token` em texto claro.
         *     O backend guarda apenas o SHA-256 do token; se o organizador perder o
         *     ingresso, o caminho e reemitir (rotacionar o token), nao recuperar.
         */
        post: operations["issueTickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** Detalhe de um ingresso */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoga um ingresso
         * @description Invalida o ingresso para check-in. Ingressos ja com status `checked_in`
         *     retornam 409 — o historico de presenca nao e reescrito.
         */
        post: operations["revokeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reemite o QR Code de um ingresso
         * @description Gera um novo `qr_token`, invalidando o anterior. Usado quando o
         *     participante perde o ingresso. So funciona em ingressos `valid`.
         */
        post: operations["reissueTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /**
         * Lista os check-ins de um evento
         * @description Ordenado do mais recente para o mais antigo. O dashboard usa esta rota
         *     para o carregamento inicial e depois recebe as novas linhas via Supabase
         *     Realtime, sem polling.
         */
        get: operations["listCheckIns"];
        put?: never;
        /**
         * Valida um QR Code e registra a entrada
         * @description Coracao do sistema. A validacao e atomica: a transacao faz
         *     `SELECT ... FOR UPDATE` na linha do ingresso antes de conferir o status,
         *     de modo que dois scanners lendo o mesmo QR ao mesmo tempo produzam
         *     exatamente um 201 e um 409.
         *
         *     O frontend do scanner mapeia cada `error.code` para um estado visual
         *     distinto (verde / amarelo / vermelho) — por isso os codigos sao estaveis.
         */
        post: operations["createCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /**
         * Estatisticas ao vivo do evento
         * @description Alimenta os cartoes e o grafico do dashboard do organizador.
         */
        get: operations["getEventStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/report-data": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /**
         * Dados agregados para o relatorio pos-evento
         * @description Payload consumido pela feature de IA de resumo pos-evento. Contem apenas
         *     numeros agregados — nenhum dado pessoal de participante — para que possa
         *     ser enviado a um modelo de linguagem sem expor a base.
         */
        get: operations["getEventReportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tickets/{qr_token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qr_token: string;
            };
            cookie?: never;
        };
        /**
         * Consulta publica de ingresso pelo token
         * @description Usada pela pagina que o participante abre no celular. O proprio token e a
         *     credencial, entao a rota nao exige JWT — mas devolve uma visao reduzida
         *     do ingresso e e limitada a 30 requisicoes por minuto por IP.
         */
        get: operations["getPublicTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Codigo estavel. Valores possiveis: UNAUTHORIZED, FORBIDDEN,
                 *     VALIDATION_ERROR, EVENT_NOT_FOUND, EVENT_NOT_ACTIVE,
                 *     EVENT_IMMUTABLE, EVENT_CAPACITY_EXCEEDED, TICKET_NOT_FOUND,
                 *     TICKET_ALREADY_CHECKED_IN, TICKET_REVOKED, TICKET_WRONG_EVENT,
                 *     RATE_LIMITED, INTERNAL_ERROR.
                 * @example TICKET_ALREADY_CHECKED_IN
                 */
                code: string;
                /** @description Texto legivel em ingles, destinado a logs e fallback de UI. */
                message: string;
                /** @description Contexto adicional especifico do codigo de erro. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Page: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
            /** @example 137 */
            total: number;
            /** @example 7 */
            total_pages: number;
        };
        Organizer: {
            /**
             * Format: uuid
             * @description Igual a claim `sub` do JWT.
             */
            id: string;
            /** Format: email */
            email: string;
            display_name?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        EventStatus: "draft" | "published" | "finished" | "cancelled";
        Event: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            title: string;
            description?: string | null;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /**
             * @description Identificador IANA.
             * @example America/Sao_Paulo
             */
            timezone: string;
            venue_name?: string | null;
            address?: string | null;
            capacity: number;
            status: components["schemas"]["EventStatus"];
            /** @description Contagem de ingressos nao revogados. */
            tickets_issued: number;
            checked_in_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EventCreate: {
            title: string;
            description?: string | null;
            /** Format: date-time */
            starts_at: string;
            /**
             * Format: date-time
             * @description Deve ser posterior a `starts_at`.
             */
            ends_at: string;
            /** @example America/Sao_Paulo */
            timezone: string;
            venue_name?: string | null;
            address?: string | null;
            capacity: number;
        };
        /** @description Todos os campos sao opcionais; ao menos um deve ser enviado. */
        EventUpdate: {
            title?: string;
            description?: string | null;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            timezone?: string;
            venue_name?: string | null;
            address?: string | null;
            capacity?: number;
        };
        /** @enum {string} */
        TicketStatus: "valid" | "checked_in" | "revoked";
        Ticket: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            event_id: string;
            attendee_name: string;
            /** Format: email */
            attendee_email?: string | null;
            /**
             * @description Categoria do ingresso (ex.: Standard, VIP).
             * @example Standard
             */
            tier?: string | null;
            status: components["schemas"]["TicketStatus"];
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            checked_in_at?: string | null;
        };
        TicketWithToken: components["schemas"]["Ticket"] & {
            /**
             * @description Token opaco de 32 bytes em base64url. Retornado apenas na emissao
             *     e na reemissao; o banco guarda somente o SHA-256.
             * @example 8Jd2mQxR7pV0aZ3nL5tYbC1eH6kU9wS4
             */
            qr_token: string;
            /**
             * @description String exata a ser codificada no QR Code, no formato
             *     `EVCK1:<qr_token>`. O scanner rejeita localmente qualquer
             *     leitura sem esse prefixo antes de chamar a API.
             * @example EVCK1:8Jd2mQxR7pV0aZ3nL5tYbC1eH6kU9wS4
             */
            qr_payload: string;
        };
        TicketBatchCreate: {
            attendees: {
                attendee_name: string;
                /** Format: email */
                attendee_email?: string | null;
                tier?: string | null;
            }[];
        };
        CheckInCreate: {
            /** @description Token extraido do QR, ja sem o prefixo `EVCK1:`. */
            qr_token: string;
            /** @description Identificacao livre do ponto de entrada (ex.: "Portaria A"). */
            device_label?: string | null;
        };
        CheckIn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ticket_id: string;
            /** Format: uuid */
            event_id: string;
            attendee_name?: string;
            /** Format: date-time */
            checked_in_at: string;
            device_label?: string | null;
            /**
             * Format: uuid
             * @description Organizador autenticado que operou o scanner.
             */
            operator_id?: string | null;
        };
        CheckInResult: {
            check_in: components["schemas"]["CheckIn"];
            ticket: components["schemas"]["Ticket"];
            /** @description Contadores no instante do check-in, para atualizar o scanner sem outra chamada. */
            event_stats: {
                tickets_issued: number;
                checked_in_count: number;
            };
        };
        TimelineBucket: {
            /** Format: date-time */
            bucket_start: string;
            count: number;
        };
        EventStats: {
            /** Format: uuid */
            event_id: string;
            tickets_issued: number;
            checked_in_count: number;
            pending_count: number;
            revoked_count: number;
            /**
             * Format: float
             * @description checked_in_count / tickets_issued, com 0 quando nao ha ingressos.
             */
            attendance_rate: number;
            /**
             * Format: float
             * @description tickets_issued / capacity.
             */
            capacity_usage?: number;
            /** Format: date-time */
            first_check_in_at?: string | null;
            /** Format: date-time */
            last_check_in_at?: string | null;
            /** @description Janela com maior volume de entradas. */
            peak_window?: {
                /** Format: date-time */
                starts_at?: string;
                /** Format: date-time */
                ends_at?: string;
                count?: number;
            } | null;
            timeline: components["schemas"]["TimelineBucket"][];
        };
        EventReportData: {
            event: {
                /** Format: uuid */
                id: string;
                title: string;
                /** Format: date-time */
                starts_at: string;
                /** Format: date-time */
                ends_at: string;
                timezone: string;
                capacity: number;
                venue_name?: string | null;
            };
            stats: components["schemas"]["EventStats"];
            /** @description Quebra por categoria de ingresso. */
            tiers: {
                tier: string | null;
                issued: number;
                checked_in: number;
            }[];
            /** @description Ingressos validos que nunca foram utilizados. */
            no_show_count?: number;
            /** @description Mediana, em minutos, entre o check-in e o inicio do evento. Negativo indica entrada apos o inicio. */
            median_minutes_before_start?: number | null;
        };
        PublicTicket: {
            attendee_name: string;
            tier?: string | null;
            status: components["schemas"]["TicketStatus"];
            /** Format: date-time */
            checked_in_at?: string | null;
            event: {
                title: string;
                /** Format: date-time */
                starts_at: string;
                /** Format: date-time */
                ends_at?: string;
                timezone: string;
                venue_name?: string | null;
                address?: string | null;
            };
        };
    };
    responses: {
        /** @description Token ausente, invalido ou expirado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Missing or invalid credentials."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Recurso inexistente ou pertencente a outro organizador */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "EVENT_NOT_FOUND",
                 *         "message": "Event not found."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Estado atual do recurso nao permite a operacao */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Corpo da requisicao invalido */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "Request body is invalid.",
                 *         "details": {
                 *           "fields": [
                 *             {
                 *               "field": "starts_at",
                 *               "message": "must be in the future"
                 *             }
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        EventId: string;
        TicketId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servico no ar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        /** @example 1.0.0 */
                        version: string;
                        /** @example 3612 */
                        uptime_seconds: number;
                        /** @enum {string} */
                        database?: "up" | "down";
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil do organizador */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organizer"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Filtra por status. Pode ser repetido. */
                status?: components["schemas"]["EventStatus"][];
                /** @description Busca case-insensitive no titulo do evento. */
                search?: string;
                page?: number;
                page_size?: number;
                sort?: "starts_at" | "-starts_at" | "created_at" | "-created_at";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina de eventos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["Event"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Evento criado */
            201: {
                headers: {
                    /** @description URI do recurso criado */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evento cancelado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Evento atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    publishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evento publicado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"][];
                /** @description Busca case-insensitive por nome ou e-mail do participante. */
                search?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina de ingressos. O `qr_token` nunca aparece aqui. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["Ticket"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    issueTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketBatchCreate"];
            };
        };
        responses: {
            /** @description Ingressos emitidos, com os tokens em texto claro */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TicketWithToken"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingresso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingresso revogado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reissueTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingresso com novo token em texto claro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketWithToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listCheckIns: {
        parameters: {
            query?: {
                /** @description Retorna apenas check-ins posteriores a este timestamp. */
                since?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina de check-ins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["CheckIn"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInCreate"];
            };
        };
        responses: {
            /** @description Check-in registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description Token nao corresponde a nenhum ingresso (`TICKET_NOT_FOUND`) ou o
             *     evento nao existe (`EVENT_NOT_FOUND`).
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Ingresso ja utilizado (`TICKET_ALREADY_CHECKED_IN`, com o check-in
             *     original em `error.details`), revogado (`TICKET_REVOKED`),
             *     pertencente a outro evento (`TICKET_WRONG_EVENT`) ou evento fora da
             *     janela de check-in (`EVENT_NOT_ACTIVE`).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getEventStats: {
        parameters: {
            query?: {
                /** @description Tamanho da janela de agregacao da linha do tempo. */
                bucket_minutes?: 5 | 10 | 15 | 30 | 60;
            };
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estatisticas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getEventReportData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados agregados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventReportData"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qr_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visao publica do ingresso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTicket"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Excesso de requisicoes */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
