/**
 * Readable aliases over the types generated from the API contract.
 *
 * Every payload type here is derived from `schema.d.ts`, which is generated by
 * `npm run api:types` from `docs/api-contract/openapi.yaml`. Never hand-write a
 * payload shape: change the contract, regenerate, and the compiler will point
 * at whatever broke.
 */
import type { components, operations } from './schema'

/* -------------------------------------------------------------------------- */
/* Resources                                                                   */
/* -------------------------------------------------------------------------- */

export type Organizer = components['schemas']['Organizer']

export type Event = components['schemas']['Event']
export type EventStatus = components['schemas']['EventStatus']
export type EventCreate = components['schemas']['EventCreate']
export type EventUpdate = components['schemas']['EventUpdate']

export type Ticket = components['schemas']['Ticket']
export type TicketStatus = components['schemas']['TicketStatus']
export type TicketWithToken = components['schemas']['TicketWithToken']
export type TicketBatchCreate = components['schemas']['TicketBatchCreate']

export type CheckIn = components['schemas']['CheckIn']
export type CheckInCreate = components['schemas']['CheckInCreate']
export type CheckInResult = components['schemas']['CheckInResult']

export type EventStats = components['schemas']['EventStats']
export type TimelineBucket = components['schemas']['TimelineBucket']
export type EventReportData = components['schemas']['EventReportData']

export type PublicTicket = components['schemas']['PublicTicket']

/** Pagination envelope shared by every list endpoint. */
export type Page = components['schemas']['Page']

/** The error envelope every 4xx/5xx response uses. */
export type ApiErrorBody = components['schemas']['Error']

/* -------------------------------------------------------------------------- */
/* Operation payloads                                                          */
/* -------------------------------------------------------------------------- */

export type HealthResponse =
  operations['getHealth']['responses'][200]['content']['application/json']

export type EventListQuery = NonNullable<operations['listEvents']['parameters']['query']>
export type EventListResponse =
  operations['listEvents']['responses'][200]['content']['application/json']

export type TicketListQuery = NonNullable<operations['listTickets']['parameters']['query']>
export type TicketListResponse =
  operations['listTickets']['responses'][200]['content']['application/json']

export type TicketBatchResponse =
  operations['issueTickets']['responses'][201]['content']['application/json']

export type CheckInListQuery = NonNullable<operations['listCheckIns']['parameters']['query']>
export type CheckInListResponse =
  operations['listCheckIns']['responses'][200]['content']['application/json']

export type EventStatsQuery = NonNullable<operations['getEventStats']['parameters']['query']>

/* -------------------------------------------------------------------------- */
/* Error codes                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Stable error codes, in contract order.
 *
 * The contract types `error.code` as a plain `string` and enumerates the values
 * only in the field description, so this union cannot be generated. It is the
 * one API-shaped declaration written by hand, and the assertion below keeps it
 * assignable to whatever the generated schema says the field is. If the
 * contract is ever revised to model `error.code` as an `enum`, delete this list
 * and derive it from `ApiErrorBody` instead.
 *
 * @see docs/api-contract/openapi.yaml — components.schemas.Error.error.code
 */
export const API_ERROR_CODES = [
  'UNAUTHORIZED',
  'FORBIDDEN',
  'VALIDATION_ERROR',
  'EVENT_NOT_FOUND',
  'EVENT_NOT_ACTIVE',
  'EVENT_IMMUTABLE',
  'EVENT_CAPACITY_EXCEEDED',
  'TICKET_NOT_FOUND',
  'TICKET_ALREADY_CHECKED_IN',
  'TICKET_REVOKED',
  'TICKET_WRONG_EVENT',
  'RATE_LIMITED',
  'INTERNAL_ERROR',
] as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[number]

/** Compile-time guard: the hand-written union must stay valid for the contract. */
type AssertAssignableToContract = ApiErrorCode extends ApiErrorBody['error']['code'] ? true : never
const _codesMatchContract: AssertAssignableToContract = true
void _codesMatchContract

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === 'string' && (API_ERROR_CODES as readonly string[]).includes(value)
}
