from enum import StrEnum


class ErrorCode(StrEnum):
    UNAUTHORIZED = "UNAUTHORIZED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_NOT_ACTIVE = "EVENT_NOT_ACTIVE"
    EVENT_IMMUTABLE = "EVENT_IMMUTABLE"
    EVENT_CAPACITY_EXCEEDED = "EVENT_CAPACITY_EXCEEDED"
    TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
    TICKET_ALREADY_CHECKED_IN = "TICKET_ALREADY_CHECKED_IN"
    TICKET_REVOKED = "TICKET_REVOKED"
    TICKET_WRONG_EVENT = "TICKET_WRONG_EVENT"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
