"""create initial schema

Revision ID: d49554e87555
Revises: 
Create Date: 2026-07-27 21:37:38.022031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49554e87555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizers'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('venue_name', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'finished', 'cancelled', name='event_status'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], name=op.f('fk_events_organizer_id_organizers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_organizer_id_starts_at', 'events', ['organizer_id', 'starts_at'], unique=False)
    op.create_index('ix_events_status_ends_at', 'events', ['status', 'ends_at'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('attendee_name', sa.String(length=120), nullable=False),
    sa.Column('attendee_email', sa.String(), nullable=True),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('valid', 'checked_in', 'revoked', name='ticket_status'), server_default='valid', nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_tickets_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_tickets_token_hash'))
    )
    op.create_index('ix_tickets_event_id_status', 'tickets', ['event_id', 'status'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_label', sa.String(length=60), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_check_ins_event_id_events')),
    sa.ForeignKeyConstraint(['operator_id'], ['organizers.id'], name=op.f('fk_check_ins_operator_id_organizers')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_check_ins_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_ins')),
    sa.UniqueConstraint('ticket_id', name=op.f('uq_check_ins_ticket_id'))
    )
    op.create_index('ix_check_ins_event_id_checked_in_at', 'check_ins', ['event_id', 'checked_in_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_ins_event_id_checked_in_at', table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index('ix_tickets_event_id_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_events_status_ends_at', table_name='events')
    op.drop_index('ix_events_organizer_id_starts_at', table_name='events')
    op.drop_table('events')
    op.drop_table('organizers')
    # ### end Alembic commands ###
